import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/generate/navbar/Navbar";
import Footer from "@/components/Footer";
import SigninModal from "@/components/modals/SigninModal";
import SearchModal from "@/components/modals/SearchModal";
import { Toaster } from "react-hot-toast";
import QuiryProvider from "@/provider/QuiryProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});
export const metadata: Metadata = {
  title: "Blog Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      suppressHydrationWarning

        className={`${poppins.className} antialiased bg-background text-text`}
      >
        <QuiryProvider>
          <Navbar />
          {children}
          <Footer />
          <SigninModal />
          <SearchModal />
          <Toaster />
        </QuiryProvider>
      </body>
    </html>
  );
}
